# Generated by Django 6.1 on 2026-08-13 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('call_sign', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('image_key', models.CharField(choices=[('malinois', 'Belgian Malinois'), ('white_lab', 'English White Labrador')], default='malinois', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_dogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
