# Generated by Django 6.1 on 2026-08-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingdog',
            name='image_key',
        ),
    ]
