# Generated by Django 6.1 on 2026-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_remove_workingdog_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingdog',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
