# Generated by Django 6.1 on 2026-08-13 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mission_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('mission_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('complete', 'Complete')], default='planned', max_length=20)),
                ('objective', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('badge_name', models.CharField(blank=True, max_length=150)),
                ('badge_motto', models.CharField(blank=True, max_length=200)),
                ('badge_colors', models.CharField(blank=True, max_length=200)),
                ('badge_symbols', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='dogs.workingdog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
