# Generated by Django 6.1 on 2026-08-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmission',
            name='badge_colors',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='trainingmission',
            name='badge_symbols',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
