# Generated by Django 6.1 on 2026-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_trainingmission_badge_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmission',
            name='mission_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
