# Generated by Django 6.1 on 2026-08-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_workingdog_gender'),
        ('missions', '0003_trainingmission_mission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmission',
            name='badge_earned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_badges', to='dogs.workingdog'),
        ),
    ]
